export const testIds = {
  panel: 'inspector-panel',
  title: 'inspector-title',
  x: 'inspector-x',
  y: 'inspector-y',
  width: 'inspector-width',
  height: 'inspector-height',
  fill: 'inspector-fill',
  stroke: 'inspector-stroke',
  multiSelectLabel: 'inspector-multi-select-label',
  xInput: 'inspector-x-input',
  yInput: 'inspector-y-input',
  widthInput: 'inspector-width-input',
  heightInput: 'inspector-height-input',
  fillInput: 'inspector-fill-input',
  strokeInput: 'inspector-stroke-input',
  arrowStartToggle: 'inspector-arrow-start-toggle',
  arrowEndToggle: 'inspector-arrow-end-toggle',
  fontFamilySelector: 'inspector-font-family-selector',
  alignmentButtons: 'inspector-alignment-buttons',
  alignmentLeft: 'inspector-alignment-left',
  alignmentCenter: 'inspector-alignment-center',
  alignmentRight: 'inspector-alignment-right',
  // Shape text alignment
  hAlignButtons: 'inspector-halign-buttons',
  hAlignLeft: 'inspector-halign-left',
  hAlignCenter: 'inspector-halign-center',
  hAlignRight: 'inspector-halign-right',
  vAlignButtons: 'inspector-valign-buttons',
  vAlignTop: 'inspector-valign-top',
  vAlignMiddle: 'inspector-valign-middle',
  vAlignBottom: 'inspector-valign-bottom',
  // Color palette
  fillSwatch: 'inspector-fill-swatch',
  strokeSwatch: 'inspector-stroke-swatch',
  colorPalette: 'inspector-color-palette',
  paletteColor: (color: string) => `inspector-palette-${color}`,
}
