export const testIds = {
  panel: 'inspector-panel',
  title: 'inspector-title',
  x: 'inspector-x',
  y: 'inspector-y',
  width: 'inspector-width',
  height: 'inspector-height',
  fill: 'inspector-fill',
  stroke: 'inspector-stroke',
  multiSelectLabel: 'inspector-multi-select-label',
  xInput: 'inspector-x-input',
  yInput: 'inspector-y-input',
  widthInput: 'inspector-width-input',
  heightInput: 'inspector-height-input',
  fillInput: 'inspector-fill-input',
  strokeInput: 'inspector-stroke-input',
}
